# Generated by Django 4.1.3 on 2022-11-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
