# Generated by Django 4.1.3 on 2022-12-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagealbum",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
