# Generated by Django 4.1.3 on 2022-12-09 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_imagealbum_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="images.imagealbum",
            ),
        ),
    ]
