# Generated by Django 4.1.3 on 2022-12-10 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("images", "0004_alter_imagealbum_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={},
        ),
        migrations.AlterModelOptions(
            name="imagealbum",
            options={},
        ),
        migrations.AddField(
            model_name="imagealbum",
            name="is_user_cover",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="imagealbum",
            name="is_user_profile",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="imagealbum",
            unique_together={("name", "user")},
        ),
    ]
