# Generated by Django 4.1.3 on 2022-12-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0005_alter_image_options_alter_imagealbum_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagealbum",
            name="is_user_cover",
        ),
        migrations.RemoveField(
            model_name="imagealbum",
            name="is_user_profile",
        ),
        migrations.AddField(
            model_name="image",
            name="is_user_cover",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="image",
            name="is_user_profile",
            field=models.BooleanField(default=False),
        ),
    ]
