# Generated by Django 4.1.3 on 2022-12-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0006_remove_imagealbum_is_user_cover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
